# Objective

Explore the dataset to identify differences between the customers of each product. You can also explore relationships between the different attributes of the customers. You can approach it from any other line of questioning that you feel could be relevant for the business. The idea is to get you comfortable working in Python.

You are expected to do the following :

1. Come up with a customer profile (characteristics of a customer) of the different products
2. Perform univariate and multivariate analyses
3. Generate a set of insights and recommendations that will help the company in targeting new customers.

Data Dictionary:

The data is about customers of the treadmill product(s) of a retail store called Cardio Good Fitness.
It contains the following variables:

1. Product          - The model no. of the treadmill
2. Age              -  Age of the customer in no of years
3. Gender           - Gender of the customer
4. Education        - Education of the customer in no. of years
5. Marital Status   - Marital status of the customer
6. Usage            - Avg. # times the customer wants to use the treadmill every week
7. Fitness          - Self rated fitness score of the customer (5 - very fit, 1 - very unfit)
8. Income           - Income of the customer
9. Miles            - Miles that a customer expects to run

**Types of Data**

1. Qualitative Data:
     * Nominal:
         * Gender
         * Marital Status
         * Product
     * Ordinal:
         * Fitness
2. Quantitative Data:
    * Discrete:
         * Income
         * Age
         * Education
    * Continuous:
         * Usage
         * Miles

# Importing libraries - pandas, numpy, seaborn, matplotlib.pyplot

In [2]:
import pandas as pd
from warnings import filterwarnings
filterwarnings(action='ignore')
from pandas.api.types import CategoricalDtype
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

import pandas_profiling
sns.set_style('whitegrid') # set the grid white
sns.set(color_codes=True)
pd.set_option('display.float_format', lambda float_num: '%.5f' % float_num) # Suppress numerical display in scientific notation

# Function Definitions

In [6]:
# EDA
def first_steps_eda(**kwargs) -> None:
  """
  Load and describe the data set
  :parameter data_frame : pandas dataframe
  """

  (df := kwargs.get("data_frame"))


  # get the size of dataframe
  print('[*] Data has {} samples and {} features.'.format(df.shape[0], df.shape[1]))
  print("-" * 100)
  print(f"[*] Features : {df.columns.to_list()}\n\n")  # get name of columns/features

  print("-" * 100)
  print("[*] Missing values :\n\n", df.isnull().sum().sort_values(ascending=False))
  print("-" * 100)
  print("[*] Percent of missing :\n\n",
        round(df.isna().sum() / df.isna().count() * 100, 2).sort_values(ascending=False))
  print("-" * 100)
  print("[*] Dataset Info :")
  print(df.info())
  print("-" * 100)
  print("[*] Unique Values: ")
  print(df.nunique())
  print("-" * 100)
  '''
  print("\n[*] Checking for Unique Values: ")
  for feature_name in df.columns.tolist():  # Check for the unique values in the data
    print("Unique values in the column '{}' are \n\n".format(feature_name), data[feature_name].unique())
    print("-" * 100)
  '''
  print("\n[*] Descriptive Statistics from the Data")
  print(f"{df.describe().T}")
  print("-" * 100)
  print("\n[*] Outliers Identification ")
  for feature in df.select_dtypes(include=np.number).columns:  # Identifying Outliers
    identify_outliers_by_feature(df=data, feature=feature)

# Identify Outliers

def identify_outliers_by_feature(df: pd.DataFrame, feature: str) -> None:
    """
    Identified Outliers in a variable
    :param df:
    :param feature:
    :return None:
        """
    # Calculate intrequatile range
    q25, q75 = np.percentile(df[feature], 25), np.percentile(df[feature], 75)
    iqr = q75 - q25
    print(f"Feature: {feature} \nIQR: {iqr}\nQ25: {q25}\nQ75: {q75}")
    # calculate the outlier cutoff
    cut_off = iqr * 1.5
    lower, upper = q25 - cut_off, q75 + cut_off
    print(f"CutOff: {cut_off}\nLower: {lower}\nUpper: {upper}")
    # identify outliers
    outliers = [x for x in df[feature] if x < lower or x > upper]
    print("Outliers Identified:")
    print(pd.Series(outliers).sort_values(ascending=False))
    print("==" * 10)

# Exploratory Data Analysis

**Understanding the Data**

- Overview of the dataset shape, datatypes - Statistical summary and check for missing values

In [5]:
data = pd.read_csv('CardioGoodFitness.csv')

In [7]:
first_steps_eda(data_frame=data)

[*] Data has 180 samples and 9 features.
----------------------------------------------------------------------------------------------------
[*] Features : ['Product', 'Age', 'Gender', 'Education', 'MaritalStatus', 'Usage', 'Fitness', 'Income', 'Miles']


----------------------------------------------------------------------------------------------------
[*] Missing values :

 Product          0
Age              0
Gender           0
Education        0
MaritalStatus    0
Usage            0
Fitness          0
Income           0
Miles            0
dtype: int64
----------------------------------------------------------------------------------------------------
[*] Percent of missing :

 Product         0.00000
Age             0.00000
Gender          0.00000
Education       0.00000
MaritalStatus   0.00000
Usage           0.00000
Fitness         0.00000
Income          0.00000
Miles           0.00000
dtype: float64
----------------------------------------------------------------------------------------------------
[*] Dataset Info :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product        180 non-null    object
 1   Age            180 non-null    int64
 2   Gender         180 non-null    object
 3   Education      180 non-null    int64
 4   MaritalStatus  180 non-null    object
 5   Usage          180 non-null    int64
 6   Fitness        180 non-null    int64
 7   Income         180 non-null    int64
 8   Miles          180 non-null    int64
dtypes: int64(6), object(3)
memory usage: 12.8+ KB
None
----------------------------------------------------------------------------------------------------
[*] Unique Values:
Product           3
Age              32
Gender            2
Education         8
MaritalStatus     2
Usage             6
Fitness           5
Income           62
Miles            37
dtype: int64
----------------------------------------------------------------------------------------------------

[*] Descriptive Statistics from the Data
              count        mean         std         min         25%  \
Age       180.00000    28.78889     6.94350    18.00000    24.00000
Education 180.00000    15.57222     1.61705    12.00000    14.00000
Usage     180.00000     3.45556     1.08480     2.00000     3.00000
Fitness   180.00000     3.31111     0.95887     1.00000     3.00000
Income    180.00000 53719.57778 16506.68423 29562.00000 44058.75000
Miles     180.00000   103.19444    51.86360    21.00000    66.00000

                  50%         75%          max
Age          26.00000    33.00000     50.00000
Education    16.00000    16.00000     21.00000
Usage         3.00000     4.00000      7.00000
Fitness       3.00000     4.00000      5.00000
Income    50596.50000 58668.00000 104581.00000
Miles        94.00000   114.75000    360.00000
----------------------------------------------------------------------------------------------------

[*] Outliers Identification
Feature: Age
IQR: 9.0
Q25: 24.0
Q75: 33.0
CutOff: 13.5
Lower: 10.5
Upper: 46.5
Outliers Identified:
1    50
2    48
4    48
0    47
3    47
dtype: int64
====================
Feature: Education
IQR: 2.0
Q25: 14.0
Q75: 16.0
CutOff: 3.0
Lower: 11.0
Upper: 19.0
Outliers Identified:
1    21
2    21
3    21
0    20
dtype: int64
====================
Feature: Usage
IQR: 1.0
Q25: 3.0
Q75: 4.0
CutOff: 1.5
Lower: 1.5
Upper: 5.5
Outliers Identified:
3    7
5    7
0    6
1    6
2    6
4    6
6    6
7    6
8    6
dtype: int64
====================
Feature: Fitness
IQR: 1.0
Q25: 3.0
Q75: 4.0
CutOff: 1.5
Lower: 1.5
Upper: 5.5
Outliers Identified:
0    1
1    1
dtype: int64
====================
Feature: Income
IQR: 14609.25
Q25: 44058.75
Q75: 58668.0
CutOff: 21913.875
Lower: 22144.875
Upper: 80581.875
Outliers Identified:
13    104581
17    104581
7     103336
8      99601
10     95866
18     95508
3      92131
11     92131
12     92131
2      90886
16     90886
6      90886
15     89641
9      89641
1      88396
4      88396
5      85906
14     83416
0      83416
dtype: int64
====================
Feature: Miles
IQR: 48.75
Q25: 66.0
Q75: 114.75
CutOff: 73.125
Lower: -7.125
Upper: 187.875
Outliers Identified:
10    360
6     300
7     280
8     260
5     240
1     212
2     200
3     200
4     200
9     200
11    200
12    200
0     188
dtype: int64
====================

## Observations:

* 180 observations and 9 features
* Features ['Product', 'Age', 'Gender', 'Education', 'MaritalStatus', 'Usage', 'Fitness', 'Income', 'Miles']
* No missing values
* Data types int64(6), object(3)
* Unique Values
Product           3
Age              32
Gender            2
Education         8
MaritalStatus     2
Usage             6
Fitness           5
Income           62
Miles            37
* Customers Age range from 18-50, Mean Age in this dataset is 28
* Educations in years from the customers range from 12-21, Education mean is 15 years
* Usage range from 2-7 times the customer wants to use the treadmill every week, Usage mean is 3